version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/codedeployresources
hooks:
  ApplicationStop:
    - location: aws_scripts/application-stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: aws_scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws_scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws_scripts/stop_server.sh
      timeout: 300
      runas: root

