version: 0.0
os: linux
files:
  - source: /
    destination: /var/acebook-test
hooks:
  AfterInstall:
    - location: aws_scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: aws_scripts/start_server.sh
      timeout: 300
      runas: ec2-user

